### ISSUE TITLE
make - fatal error

### ISSUE THREAD

**Issue by cookiemonsteruk** [pasnox/qwbfsmanager#40]
Hi. I've been unable to make version 1.2.6. The error is: 
> fatal error: openssl/md5.h: No such file or directory
> compilation terminated.
System: 
Linux mars 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 15.10).
- I have  OpenSSL 1.0.2d 9 Jul 2015.
- I tried qwbfsmanager version 1.2.5 and got the same result.
Replication:
1. qmake from sources: qmake-qt4 -r PREFIX=/usr/local ../qwbfsmanager-1.2.6/qwbfs.pro
 result: success.
2. make -j 4
 result: error .
-Lead up to the error:
`myuser@mars:~/Downloads/qwbfs-build$ make -j 4
cd libwbfs/ && make -f Makefile 
make[1]: Entering directory '/home/myuser/Downloads/qwbfs-build/libwbfs'
gcc -c -m64 -pipe -O2 -Wall -W -fPIC -D_REENTRANT -DLARGE_FILES -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../qwbfsmanager-1.2.6/libwbfs -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../qwbfsmanager-1.2.6/libwbfs -Ilibwbfs -I/home/myuser/Downloads/qwbfs-build/libwbfs/../build/release/moc -I. -o ../build/release/obj/unix/tools.o ../../qwbfsmanager-1.2.6/libwbfs/tools.c
gcc -c -m64 -pipe -O2 -Wall -W -fPIC -D_REENTRANT -DLARGE_FILES -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../qwbfsmanager-1.2.6/libwbfs -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../qwbfsmanager-1.2.6/libwbfs -Ilibwbfs -I/home/myuser/Downloads/qwbfs-build/libwbfs/../build/release/moc -I. -o ../build/release/obj/unix/ec.o ../../qwbfsmanager-1.2.6/libwbfs/ec.c
gcc -c -m64 -pipe -O2 -Wall -W -fPIC -D_REENTRANT -DLARGE_FILES -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../qwbfsmanager-1.2.6/libwbfs -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../qwbfsmanager-1.2.6/libwbfs -Ilibwbfs -I/home/myuser/Downloads/qwbfs-build/libwbfs/../build/release/moc -I. -o ../build/release/obj/unix/bn.o ../../qwbfsmanager-1.2.6/libwbfs/bn.c
gcc -c -m64 -pipe -O2 -Wall -W -fPIC -D_REENTRANT -DLARGE_FILES -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../qwbfsmanager-1.2.6/libwbfs -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../qwbfsmanager-1.2.6/libwbfs -Ilibwbfs -I/home/myuser/Downloads/qwbfs-build/libwbfs/../build/release/moc -I. -o ../build/release/obj/unix/rijndael.o ../../qwbfsmanager-1.2.6/libwbfs/rijndael.c
../../qwbfsmanager-1.2.6/libwbfs/tools.c:8:25: fatal error: openssl/md5.h: No such file or directory
compilation terminated.
../../qwbfsmanager-1.2.6/libwbfs/ec.c:27:13: warning: ‘elt_print’ defined but not used [-Wunused-function]
 static void elt_print(char *name, u8 *a)
             ^
../../qwbfsmanager-1.2.6/libwbfs/ec.c:188:12: warning: ‘point_is_on_curve’ defined but not used [-Wunused-function]
 static int point_is_on_curve(u8 *p)
            ^
Makefile:229: recipe for target '../build/release/obj/unix/tools.o' failed
make[1]: *** [../build/release/obj/unix/tools.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../../qwbfsmanager-1.2.6/libwbfs/bn.c:14:13: warning: ‘bn_print’ defined but not used [-Wunused-function]
 static void bn_print(char *name, u8 *a, u32 n)
             ^
make[1]: Leaving directory '/home/myuser/Downloads/qwbfs-build/libwbfs'
Makefile:40: recipe for target 'sub-libwbfs-make_default-ordered' failed
make: *** [sub-libwbfs-make_default-ordered] Error 2
`

**Comment by pasnox** [comment]
Hi,

You need to install the openssl dev package (openssl-dev on ubuntu systems).

**Comment by cookiemonsteruk** [comment]
I'll do that, thanks.
